### ISSUE TITLE
Subject aus Pluginaufruf wird nicht verwendet

### ISSUE THREAD

**Issue by tgerns** [JoomTools/plg_content_jtf#17]
Mein Pluginaufruf sieht wie folgt aus:
`{jtf subject=Mein Betreff}`
Der Betreff wird nicht in der E-Mail verwendet, sondern er zieht sich den Standard aus der Joomla-Konfiguration.

**Comment by degobbis** [comment]
Gefixt mit den aktuellen Versionen
https://github.com/JoomTools/plg_content_jtf/releases
