### ISSUE TITLE
Integration mit der neuen Privacy Suite von Joomla

### ISSUE THREAD

**Issue by d4shoerncheN** [JoomTools/plg_content_jtf#4]

**Comment by degobbis** [comment]
Bitte etwas mehr Input, was gemeint ist.

**Comment by d4shoerncheN** [comment]
Okay, sorry.

Das Joomla-Kontaktformular hat mit der neuen Privacy Suite ja nun auch eine Checkbox für die Datenschutzerklärung. Diese wird dann ja auch im Datenschutz-Dashboard gespeichert.

Hier wäre es doch gut, wenn deine Checkbox für die Datenschutzerklärung dann auch zusammen mit der E-Mail Adresse hinterlegt wird.

**Comment by degobbis** [comment]
Hm, meises Wissens nach findet beim absenden des Kontaktformulares keine Speicherung zur Bestätigung der Datenschutzerklärung statt, du kannst nur das Formular nicht absenden, wenn es nicht bestätigt ist.

**Comment by d4shoerncheN** [comment]
Ja, du hast Recht.
Meiner Meinung nach zwar nicht ganz konsistent, aber bin auch kein DS-GVO Fachmann. Wenn ich bei der Benutzerregistrierung die Einwilligung der Datenschutzerklärung protokollieren muss, müsste ich es rein theoretisch auch bei'm Absenden von Formularen tun.

Vielleicht verzichte ich bei Kontaktformularen auf die Checkbox und setze nur einen Hinweis.
