### ISSUE TITLE
Redirect auf Dankeseite

### ISSUE THREAD

**Issue by d4shoerncheN** [JoomTools/plg_content_jtf#5]
Moin,

wäre super, wenn man in deinem Plugin einstellen kann, dass nach dem erfolgreichen Versenden der Nachrichten auf eine definierte Dankeseite (am besten über die Menü-ID) umgeleitet wird.

Besten Dank.

**Comment by degobbis** [comment]
Danke für deinen Input, ist in der Mache.
Ich hardere noch zwischen MenuID und BeitragsID, hast du Pro und Kontras für mich?

**Comment by d4shoerncheN** [comment]
Wahrscheinlich Geschmackssache. Ich arbeite prinzipiell lieber mit MenuID, da mir die URL-Struktur da besser gefällt. Da ich dort Einfluss auf den Alias etc. nehmen kann.

**Comment by degobbis** [comment]
Umgesetzt in [3.0.0-rc23](https://github.com/JoomTools/plg_content_jtf/releases/tag/3.0.0-rc23)
