### ISSUE TITLE
Leere Mail

### ISSUE THREAD

**Issue by gogicomputers** [JoomTools/plg_content_jtf#6]
Wenn man ein Subform mit dem Parameter "multiple="false"" aufruft, dann werden die Benutzereingaben in der Mail nicht enthalten.

**Comment by degobbis** [comment]
Danke für die Meldung, werde mir das mal ansehen.

**Comment by degobbis** [comment]
@gogicomputers sollte jetzt gefixt sein mit der [3.0.0-rc25](https://github.com/JoomTools/plg_content_jtf/releases/tag/3.0.0-rc25)
Updateserver ist auch aktualisiert, das Update sollte dir angezeigt werden.
