### ISSUE TITLE
Integration der renderlabel.php

### ISSUE THREAD

**Issue by d4shoerncheN** [JoomTools/plg_content_jtf#7]
Trotz Auswahl des Frameworks "UIKit v2" oder "UIKit v3" wird die Bootstrap-Bibliothek geladen.

Hierzu gerne einmal die **renderlabel.php** aus dem Joomla Core (layouts/joomla/form) mit im Plugin aufnehmen und eine Abfrage um

`JHtml::_('bootstrap.popover');`

bauen.

Viele Grüße und vielen Dank
Toni

**Comment by degobbis** [comment]
Hallo Toni,
hab mir das jetzt mal genauer durch den Kopf gehen lassen, aber aktuell sehe ich keine Notwendigkeit das ins Plugin aufzunehmen, da im Originalen funktioniert und ich es sonst auch auf Änderungen überwachen müsste. 
Ein weiterer Grund ist die Tatsache, dass es jederzeit über ein Templateoverride überschrieben werden kann und damit auch an die eigenen Bedürfnisse.

Trotzdem danke für den Vorschlag :-)
