### ISSUE TITLE
Problem beim Dateiupload

### ISSUE THREAD

**Issue by drmenzelit** [JoomTools/plg_content_jtf#8]
Ein Upload Feld definiert:
<field name="file" type="file" description="JTF_FILE_DESC" label="JTF_FILE_LABEL" required="true" validate="file" accept=".zip,.rar,.7zip" multiple="multiple" uploadmaxsize="10" />

Upload aber nicht möglich
Ungültiges Feld:  JTF_FILE_LABEL und Error Datei nicht erlaubt

**Comment by degobbis** [comment]
Sollte mit der Version [3.0.0-rc34](https://github.com/JoomTools/plg_content_jtf/releases/tag/3.0.0-rc34) gefixt sein.
