### ISSUE TITLE
Fillout-Time bei mehreren Submit-Buttons

### ISSUE THREAD

**Issue by d4shoerncheN** [JoomTools/plg_content_jtf#9]
Moin,

es scheint ein kleines Problem mit der Fillout-Time zu geben, wenn man mehrere Submit-Buttons hat.

Aufgefallen im folgenden Szenario:

Button in der Navigationsleiste "Termin vereinbaren" öffnet ein Modal, wo das Plugin aufgerufen wird. Somit ist dieses Kontaktformular auf jeder Seite aufrufbar.

Zusätzlich gibt es einen Menüpunkt "Kontakt", wo noch einmal das Plugin im Einsatz ist (anderes Theme). 

Hier scheint die Fillout-Time nicht bei beiden zu funktionieren, nur der Button von "Kontakt" zählt runter.

Viele Grüße

**Comment by degobbis** [comment]
Hallo Toni,

danke für die Meldung, ist mit der Version [3.0.0-rc35](https://github.com/JoomTools/plg_content_jtf/releases/tag/3.0.0-rc35) behoben.

Gruß Guido
